export const SEARCH = "SEARCH";
export const SEARCH_NULL = "SEARCH_NULL";
export const ERROR = "ERROR";
export const ERROR_NO = "ERROR_NO";

export const USER_TOKEN = "USER_TOKEN";
export const USER_INFORMATION = "USER_INFORMATION";
export const IS_LOGGED_IN = "IS_LOGGED_IN";
export const IS_LOGGED_OUT = "IS_LOGGED_OUT";
export const CHAT_LIST = "CHAT_LIST";

export const SERVER_RESPONSE = "SERVER_RESPONSE";
export const SERVER_NOT_FOUND = "SERVER_ANIME_NOT_FOUND";
export const SERVER_ERROR_RESPONSE = "SERVER_ERROR_RESPONSE";
export const SERVER_RESPONSE_NULL = "SERVER_RESPONSE_NULL";

export const LANGUAGE = "LANGUAGE";
export const LANGUAGE_STATUS = "LANGUAGE_STATUS";
export const IS_ENGLISH = "IS_ENGLISH";

//Doctor
export const DOCTOR_INFORMATION = "DOCTOR_INFORMATION";
export const DOCTORS = "DOCTORS";
export const DOCTORS_STATUS = "DOCTORS_STATUS";
