const Urdu = {
  app_name: "صحت",
  email: "ای میل درج کریں",
  pass: "پاس ورڈ درج کریں",
  auth_login: {
    login: "لاگ ان کریں",
    noacc: "کیا آپ کا اکاؤنٹ نہیں ہے؟ سائن اپ",
    forget: "پاسورڈ بھول گے؟",
  },
  auth_sign_up: {
    signup: "اندراج",
    title: "عنوان",
    fname: "پہلا نام درج کریں",
    lname: "آخری نام درج کریں",
    ph: ".فون نمبر درج کریں",
    dob: "تاریخ پیدائش منتخب کریں",
    acc: "کیا آپ کا اکاؤنٹ ہے؟ لاگ ان کریں",
  },
  drawer: {
    home: "صحت",
    doctor: "کیا اپ ڈاکٹر ہیں؟",
    consult_now: "ابھی مشورہ کریں",
    appointment: "طے شدہ مُلاقات",
    medical_history: "طبی تاریخ",
    vital: "طبی صحت",
    medical_status: "طبی حیثیت",
    support: "حمائیت",
    profile: "پروفائل",
    sign_out: "لاگ آوٹ",
    preference: "ترجیح",
    language_change: "زبان کی تبدیلی",
  },
  appointment: "طے شدہ ملاقات",
  information: {
    title: "ذاتی معلومات",
    age: "عمر",
    DOB: " تاریخ پیدائش",
    email: "ای میل",
    address: " پتہ",
    gender: "صنف",
    martial_status: "ازدواجی حیثیت",
    height: "اونچائی",
    blood: " خون",
    ph: "فون",
    cnic: "شناختی کارڈ",
  },
  medical_history: {
    title: "طبی تاریخ",
    disease: "بیماری",
    symptom: "علامات",
    category: "قسم",
    reaction: "رد عمل",
    treatment: "علاج",
    pic: "تصاویر",
  },
  vital: {
    title: "حیات کے متعلق",
    heart_beat: "دل کی دھڑکن",
    blood_pressure: "بلڈ پریشر",
    weight: "وزن",
    blood_glucose: "شوگر",
  },
  medical_status: {
    title: "طبی حیثیت",
    medicine: "دوائی",
    dosage: "خوراک",
    description: "لینے کا طریقہ",
    pic: "تصاویر",
  },
};

const English = {
  app_name: "SEHAT",
  email: "Enter email",
  pass: "Enter password",
  auth_login: {
    login: "Login",
    noacc: "Don't have an account? Sign Up",
    forget: "Forgot Password?",
  },
  auth_sign_up: {
    signup: "Registration",
    title: "Title:",
    fname: "Enter First Name",
    lname: "Enter Last Name",
    ph: "Enter Phone No#",
    dob: "Select Date of Birth",
    acc: "Have an account? Login",
  },
  drawer: {
    home: "Home",
    doctor: "Are You A Doctor?",
    consult_now: "Consult Now",
    appointment: "Appointment",
    medical_history: "Medical History",
    vital: "Vital",
    medical_status: "Medical Status",
    support: "Support",
    profile: "Profile",
    sign_out: "Sign Out",
    preference: "Preference",
    language_change: "Language Change",
  },
  appointment: "Appointment",
  information: {
    title: "Personal Information",
    age: "Age",
    DOB: "Date of Birth",
    email: "Email",
    address: "Address",
    gender: "Gender",
    martial_status: "Martial Status",
    height: "Height",
    blood: "Blood",
    ph: "Phone",
    cnic: "Cnic",
  },
  medical_history: {
    title: "Medical History",
    disease: "Disease",
    symptom: "Symptom's",
    category: "Category",
    reaction: "Reaction",
    treatment: "Treatment",
    pic: "Pictures",
  },
  vital: {
    title: "Vital",
    heart_beat: "Heart Beat",
    blood_pressure: "Blood Pressure",
    weight: "Weight",
    blood_glucose: "Blood Glucose",
  },
  medical_status: {
    title: "Medical Status",
    medicine: "Medicine",
    dosage: "Dosage",
    description: "Description",
    pic: "Pictures",
  },
};

export { Urdu, English };
